name: blog
version: 0.0.1
dependencies:
  browser: any
  polymer:
    version: '1.0.0-rc.19'
    git: https://github.com/dart-lang/polymer-dart.git
  polymer_elements: '1.0.0-rc.8'
  js: '^0.6.0'
  markdown: '0.10.1'
  route: '0.4.6'
transformers:
  - polymer:
      entry_points:
        - web/index.html