name: blog
version: 0.0.1
dependencies:
  browser: any
  polymer:
    version: '1.0.0-rc.17'
    git: https://github.com/dart-lang/polymer-dart.git
  js: '^0.6.0'
transformers:
  - polymer:
      entry_points:
        - web/index.html